package com.rpgGame.netData{
	
	import flash.utils.Dictionary;
	import com.rpgGame.netData.login.message.ResCreateCharacterMessage;
	import com.rpgGame.netData.login.handler.ResCreateCharacterHandler;
	import com.rpgGame.netData.login.message.ResLoginSuccessMessage;
	import com.rpgGame.netData.login.handler.ResLoginSuccessHandler;
	import com.rpgGame.netData.login.message.ResSubstituteMessage;
	import com.rpgGame.netData.login.handler.ResSubstituteHandler;
	import com.rpgGame.netData.login.message.ResErrorMessage;
	import com.rpgGame.netData.login.handler.ResErrorHandler;
	import com.rpgGame.netData.login.message.ResQuitMessage;
	import com.rpgGame.netData.login.handler.ResQuitHandler;
	import com.rpgGame.netData.login.message.ResHeartMessage;
	import com.rpgGame.netData.login.handler.ResHeartHandler;
	import com.rpgGame.netData.map.message.ResRoundPlayerMessage;
	import com.rpgGame.netData.map.handler.ResRoundPlayerHandler;
	import com.rpgGame.netData.map.message.ResRoundMonsterMessage;
	import com.rpgGame.netData.map.handler.ResRoundMonsterHandler;
	import com.rpgGame.netData.map.message.ResRoundGoodsMessage;
	import com.rpgGame.netData.map.handler.ResRoundGoodsHandler;
	import com.rpgGame.netData.map.message.ResRoundPetMessage;
	import com.rpgGame.netData.map.handler.ResRoundPetHandler;
	import com.rpgGame.netData.map.message.ResRoundPlayerDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundPlayerDisappearHandler;
	import com.rpgGame.netData.map.message.ResRoundMonsterDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundMonsterDisappearHandler;
	import com.rpgGame.netData.map.message.ResRoundGoodsDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundGoodsDisappearHandler;
	import com.rpgGame.netData.map.message.ResRoundPetDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundPetDisappearHandler;
	import com.rpgGame.netData.map.message.ResSetPositionMessage;
	import com.rpgGame.netData.map.handler.ResSetPositionHandler;
	import com.rpgGame.netData.map.message.ResRunPositionsMessage;
	import com.rpgGame.netData.map.handler.ResRunPositionsHandler;
	import com.rpgGame.netData.map.message.ResMonsterRunPositionsMessage;
	import com.rpgGame.netData.map.handler.ResMonsterRunPositionsHandler;
	import com.rpgGame.netData.map.message.ResPlayerJumpPositionsMessage;
	import com.rpgGame.netData.map.handler.ResPlayerJumpPositionsHandler;
	import com.rpgGame.netData.map.message.ResStartBlockMessage;
	import com.rpgGame.netData.map.handler.ResStartBlockHandler;
	import com.rpgGame.netData.map.message.ResStopBlockMessage;
	import com.rpgGame.netData.map.handler.ResStopBlockHandler;
	import com.rpgGame.netData.map.message.ResMonsterStopMessage;
	import com.rpgGame.netData.map.handler.ResMonsterStopHandler;
	import com.rpgGame.netData.map.message.ResPlayerStopMessage;
	import com.rpgGame.netData.map.handler.ResPlayerStopHandler;
	import com.rpgGame.netData.map.message.ResChangeMapMessage;
	import com.rpgGame.netData.map.handler.ResChangeMapHandler;
	import com.rpgGame.netData.map.message.ResWeaponChangeMessage;
	import com.rpgGame.netData.map.handler.ResWeaponChangeHandler;
	import com.rpgGame.netData.map.message.ResArmorChangeMessage;
	import com.rpgGame.netData.map.handler.ResArmorChangeHandler;
	import com.rpgGame.netData.map.message.ResEnterMapMessage;
	import com.rpgGame.netData.map.handler.ResEnterMapHandler;
	import com.rpgGame.netData.map.message.ResPetStopMessage;
	import com.rpgGame.netData.map.handler.ResPetStopHandler;
	import com.rpgGame.netData.map.message.ResPetRunPositionsMessage;
	import com.rpgGame.netData.map.handler.ResPetRunPositionsHandler;
	import com.rpgGame.netData.map.message.ResPlayerRunEndMessage;
	import com.rpgGame.netData.map.handler.ResPlayerRunEndHandler;
	import com.rpgGame.netData.map.message.ResSendLinesMessage;
	import com.rpgGame.netData.map.handler.ResSendLinesHandler;
	import com.rpgGame.netData.map.message.ResRoundObjectsMessage;
	import com.rpgGame.netData.map.handler.ResRoundObjectsHandler;
	import com.rpgGame.netData.map.message.ResChangeMapFailedMessage;
	import com.rpgGame.netData.map.handler.ResChangeMapFailedHandler;
	import com.rpgGame.netData.map.message.ResChangeDirectMessage;
	import com.rpgGame.netData.map.handler.ResChangeDirectHandler;
	import com.rpgGame.netData.map.message.ResChangePositionMessage;
	import com.rpgGame.netData.map.handler.ResChangePositionHandler;
	import com.rpgGame.netData.map.message.ResRoundNpcMessage;
	import com.rpgGame.netData.map.handler.ResRoundNpcHandler;
	import com.rpgGame.netData.map.message.ResRoundNpcDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundNpcDisappearHandler;
	import com.rpgGame.netData.map.message.ResRoundEffectMessage;
	import com.rpgGame.netData.map.handler.ResRoundEffectHandler;
	import com.rpgGame.netData.map.message.ResRoundEffectDisappearMessage;
	import com.rpgGame.netData.map.handler.ResRoundEffectDisappearHandler;
	import com.rpgGame.netData.map.message.ResPetJumpPositionsMessage;
	import com.rpgGame.netData.map.handler.ResPetJumpPositionsHandler;
	import com.rpgGame.netData.map.message.ResPetTranMoveMessage;
	import com.rpgGame.netData.map.handler.ResPetTranMoveHandler;
	import com.rpgGame.netData.map.message.ResJumpSetPositionMessage;
	import com.rpgGame.netData.map.handler.ResJumpSetPositionHandler;
	import com.rpgGame.netData.map.message.ResDynamicgridsMessage;
	import com.rpgGame.netData.map.handler.ResDynamicgridsHandler;
	import com.rpgGame.netData.map.message.ResNewRunPositionsMessage;
	import com.rpgGame.netData.map.handler.ResNewRunPositionsHandler;
	import com.rpgGame.netData.map.message.ResChangeSexMessage;
	import com.rpgGame.netData.map.handler.ResChangeSexHandler;
	import com.rpgGame.netData.map.message.ResMoveSpeedCorrectionPercentMessage;
	import com.rpgGame.netData.map.handler.ResMoveSpeedCorrectionPercentHandler;
	import com.rpgGame.netData.map.message.ResShowEffectToClientMessage;
	import com.rpgGame.netData.map.handler.ResShowEffectToClientHandler;
	import com.rpgGame.netData.map.message.ResDoubleRepairInfosToClientMessage;
	import com.rpgGame.netData.map.handler.ResDoubleRepairInfosToClientHandler;
	import com.rpgGame.netData.map.message.ResTaskMoveToClientMessage;
	import com.rpgGame.netData.map.handler.ResTaskMoveToClientHandler;
	import com.rpgGame.netData.map.message.ResPlayerRunFailMessage;
	import com.rpgGame.netData.map.handler.ResPlayerRunFailHandler;
	import com.rpgGame.netData.map.message.ResRoundGoodsExtraMessage;
	import com.rpgGame.netData.map.handler.ResRoundGoodsExtraHandler;
	import com.rpgGame.netData.map.message.ResRoundGoodsMoneyMessage;
	import com.rpgGame.netData.map.handler.ResRoundGoodsMoneyHandler;
	import com.rpgGame.netData.map.message.SCSceneObjMoveMessage;
	import com.rpgGame.netData.map.handler.SCSceneObjMoveHandler;
	import com.rpgGame.netData.map.message.ResHelmChangeMessage;
	import com.rpgGame.netData.map.handler.ResHelmChangeHandler;
	import com.rpgGame.netData.map.message.SCAttachStateChangeMessage;
	import com.rpgGame.netData.map.handler.SCAttachStateChangeHandler;
	import com.rpgGame.netData.map.message.ResSynPlayerPositionMessage;
	import com.rpgGame.netData.map.handler.ResSynPlayerPositionHandler;
	import com.rpgGame.netData.map.message.ResSynMonsterPositionMessage;
	import com.rpgGame.netData.map.handler.ResSynMonsterPositionHandler;
	import com.rpgGame.netData.map.message.ResMapBlocksMessage;
	import com.rpgGame.netData.map.handler.ResMapBlocksHandler;
	import com.rpgGame.netData.fight.message.ResFightBroadcastMessage;
	import com.rpgGame.netData.fight.handler.ResFightBroadcastHandler;
	import com.rpgGame.netData.fight.message.ResAttackResultMessage;
	import com.rpgGame.netData.fight.handler.ResAttackResultHandler;
	import com.rpgGame.netData.fight.message.ResAttackRangeMessage;
	import com.rpgGame.netData.fight.handler.ResAttackRangeHandler;
	import com.rpgGame.netData.fight.message.ResEffectBroadcastMessage;
	import com.rpgGame.netData.fight.handler.ResEffectBroadcastHandler;
	import com.rpgGame.netData.fight.message.ResFightFailedBroadcastMessage;
	import com.rpgGame.netData.fight.handler.ResFightFailedBroadcastHandler;
	import com.rpgGame.netData.fight.message.ResFightFinishBroadcastMessage;
	import com.rpgGame.netData.fight.handler.ResFightFinishBroadcastHandler;
	import com.rpgGame.netData.fight.message.ResAttackVentToClientMessage;
	import com.rpgGame.netData.fight.handler.ResAttackVentToClientHandler;
	import com.rpgGame.netData.fight.message.ResAttackSingingToClientMessage;
	import com.rpgGame.netData.fight.handler.ResAttackSingingToClientHandler;
	import com.rpgGame.netData.fight.message.ResAttackBreakSingingToClientMessage;
	import com.rpgGame.netData.fight.handler.ResAttackBreakSingingToClientHandler;
	import com.rpgGame.netData.fight.message.ResAttackBeautyMessage;
	import com.rpgGame.netData.fight.handler.ResAttackBeautyHandler;
	import com.rpgGame.netData.fight.message.ResSkillClickFlyMessage;
	import com.rpgGame.netData.fight.handler.ResSkillClickFlyHandler;
	import com.rpgGame.netData.fight.message.ResAttackTargetMessage;
	import com.rpgGame.netData.fight.handler.ResAttackTargetHandler;
	import com.rpgGame.netData.fight.message.ResVirFightObjectAttackResultMessage;
	import com.rpgGame.netData.fight.handler.ResVirFightObjectAttackResultHandler;
	import com.rpgGame.netData.fight.message.SCAttackerResultMessage;
	import com.rpgGame.netData.fight.handler.SCAttackerResultHandler;
	import com.rpgGame.netData.fight.message.SCCancelSkillMessage;
	import com.rpgGame.netData.fight.handler.SCCancelSkillHandler;
	import com.rpgGame.netData.fight.message.SCBuffSkillMessage;
	import com.rpgGame.netData.fight.handler.SCBuffSkillHandler;
	import com.rpgGame.netData.player.message.ResMyPlayerInfoMessage;
	import com.rpgGame.netData.player.handler.ResMyPlayerInfoHandler;
	import com.rpgGame.netData.player.message.ResPlayerAddExpMessage;
	import com.rpgGame.netData.player.handler.ResPlayerAddExpHandler;
	import com.rpgGame.netData.player.message.ResPersonalNoticeMessage;
	import com.rpgGame.netData.player.handler.ResPersonalNoticeHandler;
	import com.rpgGame.netData.player.message.ResPlayerAttributeMessage;
	import com.rpgGame.netData.player.handler.ResPlayerAttributeHandler;
	import com.rpgGame.netData.player.message.BroadcastPlayerAttriChangeMessage;
	import com.rpgGame.netData.player.handler.BroadcastPlayerAttriChangeHandler;
	import com.rpgGame.netData.player.message.ResPlayerAttributesChangeMessage;
	import com.rpgGame.netData.player.handler.ResPlayerAttributesChangeHandler;
	import com.rpgGame.netData.player.message.ResPlayerBriefMessage;
	import com.rpgGame.netData.player.handler.ResPlayerBriefHandler;
	import com.rpgGame.netData.player.message.ResSyncServerTimeMessage;
	import com.rpgGame.netData.player.handler.ResSyncServerTimeHandler;
	import com.rpgGame.netData.player.message.ResPlayerStateChangeMessage;
	import com.rpgGame.netData.player.handler.ResPlayerStateChangeHandler;
	import com.rpgGame.netData.player.message.ResChangePKStateMessage;
	import com.rpgGame.netData.player.handler.ResChangePKStateHandler;
	import com.rpgGame.netData.player.message.ResChangePlayerNameToClientMessage;
	import com.rpgGame.netData.player.handler.ResChangePlayerNameToClientHandler;
	import com.rpgGame.netData.player.message.ResAutoStartStateMessage;
	import com.rpgGame.netData.player.handler.ResAutoStartStateHandler;
	import com.rpgGame.netData.player.message.RespopuGuideMessage;
	import com.rpgGame.netData.player.handler.RespopuGuideHandler;
	import com.rpgGame.netData.player.message.ResPlayerDieMessage;
	import com.rpgGame.netData.player.handler.ResPlayerDieHandler;
	import com.rpgGame.netData.player.message.ResReviveSuccessMessage;
	import com.rpgGame.netData.player.handler.ResReviveSuccessHandler;
	import com.rpgGame.netData.player.message.ResPlayerNonageStateMessage;
	import com.rpgGame.netData.player.handler.ResPlayerNonageStateHandler;
	import com.rpgGame.netData.player.message.NonagePromptMessage;
	import com.rpgGame.netData.player.handler.NonagePromptHandler;
	import com.rpgGame.netData.player.message.ResPlayerNonageTimeMessage;
	import com.rpgGame.netData.player.handler.ResPlayerNonageTimeHandler;
	import com.rpgGame.netData.player.message.ResPlayerNonageRegisterMessage;
	import com.rpgGame.netData.player.handler.ResPlayerNonageRegisterHandler;
	import com.rpgGame.netData.player.message.ResOthersPlayerInfoMessage;
	import com.rpgGame.netData.player.handler.ResOthersPlayerInfoHandler;
	import com.rpgGame.netData.player.message.ResPhoneVerificationStatusMessage;
	import com.rpgGame.netData.player.handler.ResPhoneVerificationStatusHandler;
	import com.rpgGame.netData.player.message.ResCountdownToClientMessage;
	import com.rpgGame.netData.player.handler.ResCountdownToClientHandler;
	import com.rpgGame.netData.player.message.ResRechargeInfoMessage;
	import com.rpgGame.netData.player.handler.ResRechargeInfoHandler;
	import com.rpgGame.netData.player.message.ResTotalOnlineTimeMessage;
	import com.rpgGame.netData.player.handler.ResTotalOnlineTimeHandler;
	import com.rpgGame.netData.player.message.ReskillnumToClientMessage;
	import com.rpgGame.netData.player.handler.ReskillnumToClientHandler;
	import com.rpgGame.netData.player.message.SCPlayerLevelUpMessage;
	import com.rpgGame.netData.player.handler.SCPlayerLevelUpHandler;
	import com.rpgGame.netData.player.message.SCCurrencyChangeMessage;
	import com.rpgGame.netData.player.handler.SCCurrencyChangeHandler;
	import com.rpgGame.netData.player.message.SCMaxValueChangeMessage;
	import com.rpgGame.netData.player.handler.SCMaxValueChangeHandler;
	import com.rpgGame.netData.player.message.SCNoticeMessage;
	import com.rpgGame.netData.player.handler.SCNoticeHandler;
	import com.rpgGame.netData.player.message.SCBroadcastCurrencyChangeMessage;
	import com.rpgGame.netData.player.handler.SCBroadcastCurrencyChangeHandler;
	import com.rpgGame.netData.npc.message.ResNpcServicesMessage;
	import com.rpgGame.netData.npc.handler.ResNpcServicesHandler;
	import com.rpgGame.netData.npc.message.ResStartGatherMessage;
	import com.rpgGame.netData.npc.handler.ResStartGatherHandler;
	import com.rpgGame.netData.npc.message.ResStopGatherMessage;
	import com.rpgGame.netData.npc.handler.ResStopGatherHandler;
	import com.rpgGame.netData.npc.message.ResNpcActionMessage;
	import com.rpgGame.netData.npc.handler.ResNpcActionHandler;
	import com.rpgGame.netData.npc.message.ResTaskNpcGatherFinishMessage;
	import com.rpgGame.netData.npc.handler.ResTaskNpcGatherFinishHandler;
	import com.rpgGame.netData.store.message.ResStoreItemInfosMessage;
	import com.rpgGame.netData.store.handler.ResStoreItemInfosHandler;
	import com.rpgGame.netData.store.message.ResStoreItemAddMessage;
	import com.rpgGame.netData.store.handler.ResStoreItemAddHandler;
	import com.rpgGame.netData.store.message.ResStoreItemChangeMessage;
	import com.rpgGame.netData.store.handler.ResStoreItemChangeHandler;
	import com.rpgGame.netData.store.message.ResStoreItemRemoveMessage;
	import com.rpgGame.netData.store.handler.ResStoreItemRemoveHandler;
	import com.rpgGame.netData.equip.message.WearEquipItemMessage;
	import com.rpgGame.netData.equip.handler.WearEquipItemHandler;
	import com.rpgGame.netData.equip.message.UnwearEquipItemMessage;
	import com.rpgGame.netData.equip.handler.UnwearEquipItemHandler;
	import com.rpgGame.netData.equip.message.ResKindInfosMessage;
	import com.rpgGame.netData.equip.handler.ResKindInfosHandler;
	import com.rpgGame.netData.equip.message.ResBuTianShenShiKindInfoMessage;
	import com.rpgGame.netData.equip.handler.ResBuTianShenShiKindInfoHandler;
	import com.rpgGame.netData.equip.message.ResEquipInfoMessage;
	import com.rpgGame.netData.equip.handler.ResEquipInfoHandler;
	import com.rpgGame.netData.equip.message.ResEquipOperateResultMessage;
	import com.rpgGame.netData.equip.handler.ResEquipOperateResultHandler;
	import com.rpgGame.netData.backpack.message.ResItemInfoMessage;
	import com.rpgGame.netData.backpack.handler.ResItemInfoHandler;
	import com.rpgGame.netData.backpack.message.ResItemAddMessage;
	import com.rpgGame.netData.backpack.handler.ResItemAddHandler;
	import com.rpgGame.netData.backpack.message.ResItemChangeMessage;
	import com.rpgGame.netData.backpack.handler.ResItemChangeHandler;
	import com.rpgGame.netData.backpack.message.ResItemRemoveMessage;
	import com.rpgGame.netData.backpack.handler.ResItemRemoveHandler;
	import com.rpgGame.netData.backpack.message.ResUseItemSuccessMessage;
	import com.rpgGame.netData.backpack.handler.ResUseItemSuccessHandler;
	import com.rpgGame.netData.backpack.message.ResBackpackFullMessage;
	import com.rpgGame.netData.backpack.handler.ResBackpackFullHandler;
	import com.rpgGame.netData.backpack.message.ResTakeUpSuccessMessage;
	import com.rpgGame.netData.backpack.handler.ResTakeUpSuccessHandler;
	import com.rpgGame.netData.backpack.message.ResCellTimeMessage;
	import com.rpgGame.netData.backpack.handler.ResCellTimeHandler;
	import com.rpgGame.netData.backpack.message.ResOpenCellResultMessage;
	import com.rpgGame.netData.backpack.handler.ResOpenCellResultHandler;
	import com.rpgGame.netData.backpack.message.ResPrivateItemInfoMessage;
	import com.rpgGame.netData.backpack.handler.ResPrivateItemInfoHandler;
	import com.rpgGame.netData.backpack.message.ResAddPrivateItemMessage;
	import com.rpgGame.netData.backpack.handler.ResAddPrivateItemHandler;
	import com.rpgGame.netData.backpack.message.ResRemovePrivateItemMessage;
	import com.rpgGame.netData.backpack.handler.ResRemovePrivateItemHandler;
	import com.rpgGame.netData.backpack.message.ResChangeBindItemMessage;
	import com.rpgGame.netData.backpack.handler.ResChangeBindItemHandler;
	import com.rpgGame.netData.backpack.message.ResChangeLimitItemMessage;
	import com.rpgGame.netData.backpack.handler.ResChangeLimitItemHandler;
	import com.rpgGame.netData.team.message.ResTeamInfoMessage;
	import com.rpgGame.netData.team.handler.ResTeamInfoHandler;
	import com.rpgGame.netData.team.message.ResApplyClientMessage;
	import com.rpgGame.netData.team.handler.ResApplyClientHandler;
	import com.rpgGame.netData.team.message.ResLeaveTeamMessage;
	import com.rpgGame.netData.team.handler.ResLeaveTeamHandler;
	import com.rpgGame.netData.team.message.ResInviteTeamMessage;
	import com.rpgGame.netData.team.handler.ResInviteTeamHandler;
	import com.rpgGame.netData.team.message.ResTeamExteriorClientMessage;
	import com.rpgGame.netData.team.handler.ResTeamExteriorClientHandler;
	import com.rpgGame.netData.team.message.ResAppointClientMessage;
	import com.rpgGame.netData.team.handler.ResAppointClientHandler;
	import com.rpgGame.netData.team.message.ResMapSearchTeamInfoClientMessage;
	import com.rpgGame.netData.team.handler.ResMapSearchTeamInfoClientHandler;
	import com.rpgGame.netData.team.message.ResMapSearchPlayerInfoClientMessage;
	import com.rpgGame.netData.team.handler.ResMapSearchPlayerInfoClientHandler;
	import com.rpgGame.netData.team.message.ResTeamSynPosClientMessage;
	import com.rpgGame.netData.team.handler.ResTeamSynPosClientHandler;
	import com.rpgGame.netData.team.message.ResTeamSynMemberinfoClientMessage;
	import com.rpgGame.netData.team.handler.ResTeamSynMemberinfoClientHandler;
	import com.rpgGame.netData.team.message.ResSetTeamOptionsClientMessage;
	import com.rpgGame.netData.team.handler.ResSetTeamOptionsClientHandler;
	import com.rpgGame.netData.team.message.ResGenericSearchToClientMessage;
	import com.rpgGame.netData.team.handler.ResGenericSearchToClientHandler;
	import com.rpgGame.netData.guild.message.ResGuildGetGuildListToClientMessage;
	import com.rpgGame.netData.guild.handler.ResGuildGetGuildListToClientHandler;
	import com.rpgGame.netData.guild.message.ResGuildApplyAddMessage;
	import com.rpgGame.netData.guild.handler.ResGuildApplyAddHandler;
	import com.rpgGame.netData.guild.message.ResGuildInviteAddMessage;
	import com.rpgGame.netData.guild.handler.ResGuildInviteAddHandler;
	import com.rpgGame.netData.guild.message.ResGuildGetMemberListMessage;
	import com.rpgGame.netData.guild.handler.ResGuildGetMemberListHandler;
	import com.rpgGame.netData.guild.message.ResGuildGetEventListMessage;
	import com.rpgGame.netData.guild.handler.ResGuildGetEventListHandler;
	import com.rpgGame.netData.guild.message.ResGuildGuildInfoMessage;
	import com.rpgGame.netData.guild.handler.ResGuildGuildInfoHandler;
	import com.rpgGame.netData.guild.message.ResGuildHandleResultMessage;
	import com.rpgGame.netData.guild.handler.ResGuildHandleResultHandler;
	import com.rpgGame.netData.guild.message.ResNoticeGuildBossApplyMessage;
	import com.rpgGame.netData.guild.handler.ResNoticeGuildBossApplyHandler;
	import com.rpgGame.netData.guild.message.ResRoundGuildChangeMessage;
	import com.rpgGame.netData.guild.handler.ResRoundGuildChangeHandler;
	import com.rpgGame.netData.guild.message.ResApplyUnionGuildMessage;
	import com.rpgGame.netData.guild.handler.ResApplyUnionGuildHandler;
	import com.rpgGame.netData.guild.message.ResGuildDiplomacyInfosMessage;
	import com.rpgGame.netData.guild.handler.ResGuildDiplomacyInfosHandler;
	import com.rpgGame.netData.guild.message.ResSearchGuildMessage;
	import com.rpgGame.netData.guild.handler.ResSearchGuildHandler;
	import com.rpgGame.netData.guild.message.ResDevoteGuildMessage;
	import com.rpgGame.netData.guild.handler.ResDevoteGuildHandler;
	import com.rpgGame.netData.guild.message.ResSendGuildStoreInfoMessage;
	import com.rpgGame.netData.guild.handler.ResSendGuildStoreInfoHandler;
	import com.rpgGame.netData.guild.message.ResGuildItemAddMessage;
	import com.rpgGame.netData.guild.handler.ResGuildItemAddHandler;
	import com.rpgGame.netData.guild.message.ResGuildItemChangeMessage;
	import com.rpgGame.netData.guild.handler.ResGuildItemChangeHandler;
	import com.rpgGame.netData.guild.message.ResGuildItemRemoveMessage;
	import com.rpgGame.netData.guild.handler.ResGuildItemRemoveHandler;
	import com.rpgGame.netData.guild.message.ResGuildStoreOptAddMessage;
	import com.rpgGame.netData.guild.handler.ResGuildStoreOptAddHandler;
	import com.rpgGame.netData.guild.message.ResGuildStoreApplylistMessage;
	import com.rpgGame.netData.guild.handler.ResGuildStoreApplylistHandler;
	import com.rpgGame.netData.guild.message.ResGuildBossListMessage;
	import com.rpgGame.netData.guild.handler.ResGuildBossListHandler;
	import com.rpgGame.netData.guild.message.ResUpdateGuildBossMessage;
	import com.rpgGame.netData.guild.handler.ResUpdateGuildBossHandler;
	import com.rpgGame.netData.guild.message.ResGuildZoneResultMessage;
	import com.rpgGame.netData.guild.handler.ResGuildZoneResultHandler;
	import com.rpgGame.netData.chat.message.ResChatMessage;
	import com.rpgGame.netData.chat.handler.ResChatHandler;
	import com.rpgGame.netData.chat.message.ResChatRecordMessage;
	import com.rpgGame.netData.chat.handler.ResChatRecordHandler;
	import com.rpgGame.netData.chat.message.ResOfflineChatCountMessage;
	import com.rpgGame.netData.chat.handler.ResOfflineChatCountHandler;
	import com.rpgGame.netData.monster.message.ResMonsterHpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterHpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterMpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterMpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterSpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterSpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterMaxHpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterMaxHpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterMaxMpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterMaxMpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterMaxSpChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterMaxSpChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterSpeedChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterSpeedChangeHandler;
	import com.rpgGame.netData.monster.message.ResMonsterDieMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterDieHandler;
	import com.rpgGame.netData.monster.message.ResMonsterReviveMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterReviveHandler;
	import com.rpgGame.netData.monster.message.ResMonsterSayMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterSayHandler;
	import com.rpgGame.netData.monster.message.ResMonsterHpRateChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterHpRateChangeHandler;
	import com.rpgGame.netData.monster.message.ResWGBossListToClientMessage;
	import com.rpgGame.netData.monster.handler.ResWGBossListToClientHandler;
	import com.rpgGame.netData.monster.message.ResWGBossInfoToClientMessage;
	import com.rpgGame.netData.monster.handler.ResWGBossInfoToClientHandler;
	import com.rpgGame.netData.monster.message.ResBossDamageInfosToClientMessage;
	import com.rpgGame.netData.monster.handler.ResBossDamageInfosToClientHandler;
	import com.rpgGame.netData.monster.message.ResMonsterAIStepChangeMessage;
	import com.rpgGame.netData.monster.handler.ResMonsterAIStepChangeHandler;
	import com.rpgGame.netData.monster.message.ResBossOwerInfoToClientMessage;
	import com.rpgGame.netData.monster.handler.ResBossOwerInfoToClientHandler;
	import com.rpgGame.netData.fightpower.message.ResFightPowerToClientMessage;
	import com.rpgGame.netData.fightpower.handler.ResFightPowerToClientHandler;
	import com.rpgGame.netData.friend.message.ResFriendListInfoMessage;
	import com.rpgGame.netData.friend.handler.ResFriendListInfoHandler;
	import com.rpgGame.netData.friend.message.ResOperationFriendResultMessage;
	import com.rpgGame.netData.friend.handler.ResOperationFriendResultHandler;
	import com.rpgGame.netData.friend.message.ResOperationFriendMsgMessage;
	import com.rpgGame.netData.friend.handler.ResOperationFriendMsgHandler;
	import com.rpgGame.netData.friend.message.ResPlayerFriendSettingMessage;
	import com.rpgGame.netData.friend.handler.ResPlayerFriendSettingHandler;
	import com.rpgGame.netData.mail.message.ResAllMailsMessage;
	import com.rpgGame.netData.mail.handler.ResAllMailsHandler;
	import com.rpgGame.netData.mail.message.ResMailDetailInfoMessage;
	import com.rpgGame.netData.mail.handler.ResMailDetailInfoHandler;
	import com.rpgGame.netData.mail.message.ResRecevieNewMailMessage;
	import com.rpgGame.netData.mail.handler.ResRecevieNewMailHandler;
	import com.rpgGame.netData.mail.message.ResGetMailAttachmentSueccessMessage;
	import com.rpgGame.netData.mail.handler.ResGetMailAttachmentSueccessHandler;
	import com.rpgGame.netData.mail.message.SCDeleteResultMessage;
	import com.rpgGame.netData.mail.handler.SCDeleteResultHandler;
	import com.rpgGame.netData.buff.message.ResBuffsMessage;
	import com.rpgGame.netData.buff.handler.ResBuffsHandler;
	import com.rpgGame.netData.buff.message.ResAddBuffMessage;
	import com.rpgGame.netData.buff.handler.ResAddBuffHandler;
	import com.rpgGame.netData.buff.message.ResRemoveBuffMessage;
	import com.rpgGame.netData.buff.handler.ResRemoveBuffHandler;
	import com.rpgGame.netData.buff.message.ResBuffInfoMessage;
	import com.rpgGame.netData.buff.handler.ResBuffInfoHandler;
	import com.rpgGame.netData.buff.message.ResChangeBuffMessage;
	import com.rpgGame.netData.buff.handler.ResChangeBuffHandler;
	import com.rpgGame.netData.buff.message.ResShowBuffInfoMessage;
	import com.rpgGame.netData.buff.handler.ResShowBuffInfoHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsLaunchMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsLaunchHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsCanceledMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsCanceledHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsStartMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsStartHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsIntoItemMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsIntoItemHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsRemoveItemMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsRemoveItemHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsChangeGoldMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsChangeGoldHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsChangeYuanbaoMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsChangeYuanbaoHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsSetStateMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsSetStateHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsSuccessMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsSuccessHandler;
	import com.rpgGame.netData.transactions.message.ResTransactionsErrorMessage;
	import com.rpgGame.netData.transactions.handler.ResTransactionsErrorHandler;
	import com.rpgGame.netData.transactions.message.ResTmpYuanbaoLogMessage;
	import com.rpgGame.netData.transactions.handler.ResTmpYuanbaoLogHandler;
	import com.rpgGame.netData.skill.message.ResSkillInfosMessage;
	import com.rpgGame.netData.skill.handler.ResSkillInfosHandler;
	import com.rpgGame.netData.skill.message.ResSkillAddMessage;
	import com.rpgGame.netData.skill.handler.ResSkillAddHandler;
	import com.rpgGame.netData.skill.message.ResSkillStartLevelUpMessage;
	import com.rpgGame.netData.skill.handler.ResSkillStartLevelUpHandler;
	import com.rpgGame.netData.skill.message.ResSkillRemoveMessage;
	import com.rpgGame.netData.skill.handler.ResSkillRemoveHandler;
	import com.rpgGame.netData.skill.message.ResSkillResetEffectsidMessage;
	import com.rpgGame.netData.skill.handler.ResSkillResetEffectsidHandler;
	import com.rpgGame.netData.skill.message.ResSkillChangeMessage;
	import com.rpgGame.netData.skill.handler.ResSkillChangeHandler;
	import com.rpgGame.netData.task.message.ResTaskInformationMessage;
	import com.rpgGame.netData.task.handler.ResTaskInformationHandler;
	import com.rpgGame.netData.task.message.ResTaskAcceptedMessage;
	import com.rpgGame.netData.task.handler.ResTaskAcceptedHandler;
	import com.rpgGame.netData.task.message.ResTaskChangeMessage;
	import com.rpgGame.netData.task.handler.ResTaskChangeHandler;
	import com.rpgGame.netData.task.message.ResTaskSubmitedMessage;
	import com.rpgGame.netData.task.handler.ResTaskSubmitedHandler;
	import com.rpgGame.netData.task.message.ResTreasureBoxInfoMessage;
	import com.rpgGame.netData.task.handler.ResTreasureBoxInfoHandler;
	import com.rpgGame.netData.task.message.ResTreasureBoxRewardListMessage;
	import com.rpgGame.netData.task.handler.ResTreasureBoxRewardListHandler;
	import com.rpgGame.netData.task.message.ResGetTreasureBoxRewardMessage;
	import com.rpgGame.netData.task.handler.ResGetTreasureBoxRewardHandler;
	import com.rpgGame.netData.zhangong.message.SCMeritoriousInfoListMessage;
	import com.rpgGame.netData.zhangong.handler.SCMeritoriousInfoListHandler;
	import com.rpgGame.netData.zhangong.message.SCMeritoriousUpgradeResultMessage;
	import com.rpgGame.netData.zhangong.handler.SCMeritoriousUpgradeResultHandler;
	import com.rpgGame.netData.junjie.message.SCJunJieInfoListMessage;
	import com.rpgGame.netData.junjie.handler.SCJunJieInfoListHandler;
	import com.rpgGame.netData.junjie.message.SCJunJieActivateResultMessage;
	import com.rpgGame.netData.junjie.handler.SCJunJieActivateResultHandler;
	import com.rpgGame.netData.junjie.message.SCJunJieInfoUpdateListMessage;
	import com.rpgGame.netData.junjie.handler.SCJunJieInfoUpdateListHandler;
	import com.rpgGame.netData.junjie.message.SCUpdateRoundMessage;
	import com.rpgGame.netData.junjie.handler.SCUpdateRoundHandler;
	import com.rpgGame.netData.card.message.ResCardToClientMessage;
	import com.rpgGame.netData.card.handler.ResCardToClientHandler;
	import com.rpgGame.netData.top.message.ResToplistToClientMessage;
	import com.rpgGame.netData.top.handler.ResToplistToClientHandler;
	import com.rpgGame.netData.top.message.ResListLeaderToClientMessage;
	import com.rpgGame.netData.top.handler.ResListLeaderToClientHandler;
	import com.rpgGame.netData.top.message.ResWorshipValueMessage;
	import com.rpgGame.netData.top.handler.ResWorshipValueHandler;
	import com.rpgGame.netData.top.message.ResRankRewardMessage;
	import com.rpgGame.netData.top.handler.ResRankRewardHandler;
	import com.rpgGame.netData.top.message.ResWorshipCountMessage;
	import com.rpgGame.netData.top.handler.ResWorshipCountHandler;
	import com.rpgGame.netData.stall.message.ResStallGoodsMessage;
	import com.rpgGame.netData.stall.handler.ResStallGoodsHandler;
	import com.rpgGame.netData.stall.message.ResStallInfoMessage;
	import com.rpgGame.netData.stall.handler.ResStallInfoHandler;
	import com.rpgGame.netData.stall.message.ResChangeStallNameMessage;
	import com.rpgGame.netData.stall.handler.ResChangeStallNameHandler;
	import com.rpgGame.netData.stall.message.ResStallGoodsSearchMessage;
	import com.rpgGame.netData.stall.handler.ResStallGoodsSearchHandler;
	import com.rpgGame.netData.stall.message.ResLookStallLogMessage;
	import com.rpgGame.netData.stall.handler.ResLookStallLogHandler;
	import com.rpgGame.netData.horse.message.SCHorseAllInfoToClientMessage;
	import com.rpgGame.netData.horse.handler.SCHorseAllInfoToClientHandler;
	import com.rpgGame.netData.horse.message.SCHorseIllusionToClientMessage;
	import com.rpgGame.netData.horse.handler.SCHorseIllusionToClientHandler;
	import com.rpgGame.netData.horse.message.SCHorseUpResultToClientMessage;
	import com.rpgGame.netData.horse.handler.SCHorseUpResultToClientHandler;
	import com.rpgGame.netData.horse.message.SCExtraItemNumMessage;
	import com.rpgGame.netData.horse.handler.SCExtraItemNumHandler;
	import com.rpgGame.netData.pet.message.ResPetDieBroadcastMessage;
	import com.rpgGame.netData.pet.handler.ResPetDieBroadcastHandler;
	import com.rpgGame.netData.pet.message.ResPetTargetMessage;
	import com.rpgGame.netData.pet.handler.ResPetTargetHandler;
	import com.rpgGame.netData.pet.message.ResPetHpChangeMessage;
	import com.rpgGame.netData.pet.handler.ResPetHpChangeHandler;
	import com.rpgGame.netData.pet.message.ResPetDebutMessage;
	import com.rpgGame.netData.pet.handler.ResPetDebutHandler;
	import com.rpgGame.netData.pet.message.ResPetListMessage;
	import com.rpgGame.netData.pet.handler.ResPetListHandler;
	import com.rpgGame.netData.pet.message.ResPetAttributeMessage;
	import com.rpgGame.netData.pet.handler.ResPetAttributeHandler;
	import com.rpgGame.netData.pet.message.ResPetRankChangeMessage;
	import com.rpgGame.netData.pet.handler.ResPetRankChangeHandler;
	import com.rpgGame.netData.pet.message.ResPetReliefTimeMessage;
	import com.rpgGame.netData.pet.handler.ResPetReliefTimeHandler;
	import com.rpgGame.netData.shop.message.SCSaleSuccessMessage;
	import com.rpgGame.netData.shop.handler.SCSaleSuccessHandler;
	import com.rpgGame.netData.shop.message.SCRebuySuccessMessage;
	import com.rpgGame.netData.shop.handler.SCRebuySuccessHandler;
	import com.rpgGame.netData.shop.message.SCRebuyItemInfosMessage;
	import com.rpgGame.netData.shop.handler.SCRebuyItemInfosHandler;
	import com.rpgGame.netData.shop.message.SCBuyItemResultMessage;
	import com.rpgGame.netData.shop.handler.SCBuyItemResultHandler;
	import com.rpgGame.netData.shop.message.SCSendShopListMessage;
	import com.rpgGame.netData.shop.handler.SCSendShopListHandler;
	import com.rpgGame.netData.shop.message.SCSendShopItemChangeMessage;
	import com.rpgGame.netData.shop.handler.SCSendShopItemChangeHandler;
	import com.rpgGame.netData.achievement.message.ResSendAchievementDataInfoMessage;
	import com.rpgGame.netData.achievement.handler.ResSendAchievementDataInfoHandler;
	import com.rpgGame.netData.achievement.message.ResSendFinishAchievementMessage;
	import com.rpgGame.netData.achievement.handler.ResSendFinishAchievementHandler;
	import com.rpgGame.netData.achievement.message.ResSendGetAchievementAwardMessage;
	import com.rpgGame.netData.achievement.handler.ResSendGetAchievementAwardHandler;
	import com.rpgGame.netData.sign.message.ResSendSignInfoToClientMessage;
	import com.rpgGame.netData.sign.handler.ResSendSignInfoToClientHandler;
	import com.rpgGame.netData.sign.message.ResSendSignResultToClientMessage;
	import com.rpgGame.netData.sign.handler.ResSendSignResultToClientHandler;
	import com.rpgGame.netData.sign.message.ResSignSumAwardResultToClientMessage;
	import com.rpgGame.netData.sign.handler.ResSignSumAwardResultToClientHandler;
	import com.rpgGame.netData.zone.message.ResZoneFailureToClientMessage;
	import com.rpgGame.netData.zone.handler.ResZoneFailureToClientHandler;
	import com.rpgGame.netData.zone.message.ResZoneCommonPanelInfoMessage;
	import com.rpgGame.netData.zone.handler.ResZoneCommonPanelInfoHandler;
	import com.rpgGame.netData.zone.message.ResZoneCommonTrackInfoMessage;
	import com.rpgGame.netData.zone.handler.ResZoneCommonTrackInfoHandler;
	import com.rpgGame.netData.zone.message.ResZoneCommonTrackCompactInfoMessage;
	import com.rpgGame.netData.zone.handler.ResZoneCommonTrackCompactInfoHandler;
	import com.rpgGame.netData.zone.message.ResZoneCommonResultInfoMessage;
	import com.rpgGame.netData.zone.handler.ResZoneCommonResultInfoHandler;
	import com.rpgGame.netData.zone.message.ResJuegMingTaInfoMessage;
	import com.rpgGame.netData.zone.handler.ResJuegMingTaInfoHandler;
	import com.rpgGame.netData.zone.message.ResJueMingTaSweepInfoMessage;
	import com.rpgGame.netData.zone.handler.ResJueMingTaSweepInfoHandler;
	import com.rpgGame.netData.zone.message.ResJiaoChangInfoMessage;
	import com.rpgGame.netData.zone.handler.ResJiaoChangInfoHandler;
	import com.rpgGame.netData.zone.message.ResJiaoChangResultInfoMessage;
	import com.rpgGame.netData.zone.handler.ResJiaoChangResultInfoHandler;
	import com.rpgGame.netData.zone.message.ResTreeAndMonsterRewardInfoMessage;
	import com.rpgGame.netData.zone.handler.ResTreeAndMonsterRewardInfoHandler;
	import com.rpgGame.netData.zone.message.ResSuMingDuiJueInfoMessage;
	import com.rpgGame.netData.zone.handler.ResSuMingDuiJueInfoHandler;
	import com.rpgGame.netData.zone.message.ResLeaderBossPanelInfoMessage;
	import com.rpgGame.netData.zone.handler.ResLeaderBossPanelInfoHandler;
	import com.rpgGame.netData.zone.message.ResWuShenDianFightInfoMessage;
	import com.rpgGame.netData.zone.handler.ResWuShenDianFightInfoHandler;
	import com.rpgGame.netData.zone.message.ResWuShenDianRewardInfoMessage;
	import com.rpgGame.netData.zone.handler.ResWuShenDianRewardInfoHandler;
	import com.rpgGame.netData.zone.message.ResBossGuideInfoMessage;
	import com.rpgGame.netData.zone.handler.ResBossGuideInfoHandler;
	import com.rpgGame.netData.zone.message.ResWuShenDianAnimationMessage;
	import com.rpgGame.netData.zone.handler.ResWuShenDianAnimationHandler;
	import com.rpgGame.netData.zone.message.SCClientTriggerValiedMessage;
	import com.rpgGame.netData.zone.handler.SCClientTriggerValiedHandler;
	import com.rpgGame.netData.zone.message.SCEnterZoneMessage;
	import com.rpgGame.netData.zone.handler.SCEnterZoneHandler;
	import com.rpgGame.netData.zone.message.SCOutZoneMessage;
	import com.rpgGame.netData.zone.handler.SCOutZoneHandler;
	import com.rpgGame.netData.zone.message.SCZoneStageChangeMessage;
	import com.rpgGame.netData.zone.handler.SCZoneStageChangeHandler;
	import com.rpgGame.netData.zone.message.SCRemainTimeMessage;
	import com.rpgGame.netData.zone.handler.SCRemainTimeHandler;
	import com.rpgGame.netData.zone.message.SCKillInfosMessage;
	import com.rpgGame.netData.zone.handler.SCKillInfosHandler;
	import com.rpgGame.netData.zone.message.SCKillInfoMessage;
	import com.rpgGame.netData.zone.handler.SCKillInfoHandler;
	import com.rpgGame.netData.zone.message.SCCurTriggerMessage;
	import com.rpgGame.netData.zone.handler.SCCurTriggerHandler;
	import com.rpgGame.netData.zone.message.SCMultiZoneResultMessage;
	import com.rpgGame.netData.zone.handler.SCMultiZoneResultHandler;
	import com.rpgGame.netData.zone.message.SCMultiZoneRewardMessage;
	import com.rpgGame.netData.zone.handler.SCMultiZoneRewardHandler;
	import com.rpgGame.netData.zone.message.SCMultiZonePanelInfosMessage;
	import com.rpgGame.netData.zone.handler.SCMultiZonePanelInfosHandler;
	import com.rpgGame.netData.zone.message.SCMultiZonePanelSingleInfoMessage;
	import com.rpgGame.netData.zone.handler.SCMultiZonePanelSingleInfoHandler;
	import com.rpgGame.netData.treasurehunt.message.ResHuntItemAddMessageMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResHuntItemAddMessageHandler;
	import com.rpgGame.netData.treasurehunt.message.ResHuntItemChangeMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResHuntItemChangeHandler;
	import com.rpgGame.netData.treasurehunt.message.ResHuntItemRemoveMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResHuntItemRemoveHandler;
	import com.rpgGame.netData.treasurehunt.message.ResSendHuntStoreInfoMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResSendHuntStoreInfoHandler;
	import com.rpgGame.netData.treasurehunt.message.ResSendHuntHistoryInfoMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResSendHuntHistoryInfoHandler;
	import com.rpgGame.netData.treasurehunt.message.ResHuntPanlInfoMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResHuntPanlInfoHandler;
	import com.rpgGame.netData.treasurehunt.message.ResHuntRewardInfosMessage;
	import com.rpgGame.netData.treasurehunt.handler.ResHuntRewardInfosHandler;
	import com.rpgGame.netData.activities.message.ResActivitiesInfoMessage;
	import com.rpgGame.netData.activities.handler.ResActivitiesInfoHandler;
	import com.rpgGame.netData.activities.message.ResActivitiesGetRewardInfoMessage;
	import com.rpgGame.netData.activities.handler.ResActivitiesGetRewardInfoHandler;
	import com.rpgGame.netData.activities.message.ResActivitiesRefreshMessage;
	import com.rpgGame.netData.activities.handler.ResActivitiesRefreshHandler;
	import com.rpgGame.netData.newactivities.message.ResNewActivitiesInfoMessage;
	import com.rpgGame.netData.newactivities.handler.ResNewActivitiesInfoHandler;
	import com.rpgGame.netData.newactivities.message.ResNewGetRewardMessage;
	import com.rpgGame.netData.newactivities.handler.ResNewGetRewardHandler;
	import com.rpgGame.netData.vip.message.ResVipPanelMessage;
	import com.rpgGame.netData.vip.handler.ResVipPanelHandler;
	import com.rpgGame.netData.grown.message.ResGrownInfoMessage;
	import com.rpgGame.netData.grown.handler.ResGrownInfoHandler;
	import com.rpgGame.netData.grown.message.ResGotSuccessMessage;
	import com.rpgGame.netData.grown.handler.ResGotSuccessHandler;
	import com.rpgGame.netData.warmark.message.ResWarMarkListMessage;
	import com.rpgGame.netData.warmark.handler.ResWarMarkListHandler;
	import com.rpgGame.netData.warmark.message.ResUpdateWarmarkMessage;
	import com.rpgGame.netData.warmark.handler.ResUpdateWarmarkHandler;
	import com.rpgGame.netData.gm.message.ResGmLevelMessage;
	import com.rpgGame.netData.gm.handler.ResGmLevelHandler;
	import com.rpgGame.netData.drop.message.ResDropRollItemInfoMessage;
	import com.rpgGame.netData.drop.handler.ResDropRollItemInfoHandler;
	import com.rpgGame.netData.drop.message.ResDropRollResultInfoMessage;
	import com.rpgGame.netData.drop.handler.ResDropRollResultInfoHandler;
	import com.rpgGame.netData.drop.message.ResGetRollItemMessage;
	import com.rpgGame.netData.drop.handler.ResGetRollItemHandler;
	import com.rpgGame.netData.refining.message.ResRefiningInfoMessage;
	import com.rpgGame.netData.refining.handler.ResRefiningInfoHandler;
	import com.rpgGame.netData.refining.message.ResStrengthenResultMessage;
	import com.rpgGame.netData.refining.handler.ResStrengthenResultHandler;
	import com.rpgGame.netData.refining.message.ResRefiningItemInfosMessage;
	import com.rpgGame.netData.refining.handler.ResRefiningItemInfosHandler;
	import com.rpgGame.netData.refining.message.ResExchangeResultMessage;
	import com.rpgGame.netData.refining.handler.ResExchangeResultHandler;
	import com.rpgGame.netData.vitality.message.ResSendVitalityInfoMessage;
	import com.rpgGame.netData.vitality.handler.ResSendVitalityInfoHandler;
	import com.rpgGame.netData.offlineres.message.ResOfflineAwardPanelMessage;
	import com.rpgGame.netData.offlineres.handler.ResOfflineAwardPanelHandler;
	import com.rpgGame.netData.offlineres.message.ResOfflineResPanelMessage;
	import com.rpgGame.netData.offlineres.handler.ResOfflineResPanelHandler;
	import com.rpgGame.netData.offlineres.message.ResGetOfflineSucMessage;
	import com.rpgGame.netData.offlineres.handler.ResGetOfflineSucHandler;
	import com.rpgGame.netData.offlineres.message.ResGetResSuccessMessage;
	import com.rpgGame.netData.offlineres.handler.ResGetResSuccessHandler;
	import com.rpgGame.netData.drop.message.ResDropRollItemInfoMessage;
	import com.rpgGame.netData.drop.handler.ResDropRollItemInfoHandler;
	import com.rpgGame.netData.drop.message.ResDropRollResultInfoMessage;
	import com.rpgGame.netData.drop.handler.ResDropRollResultInfoHandler;
	import com.rpgGame.netData.drop.message.ResGetRollItemMessage;
	import com.rpgGame.netData.drop.handler.ResGetRollItemHandler;
	import com.rpgGame.netData.drop.message.SCChangeMasterMessage;
	import com.rpgGame.netData.drop.handler.SCChangeMasterHandler;
	import com.rpgGame.netData.prestige.message.ResPrestigeInfoMessage;
	import com.rpgGame.netData.prestige.handler.ResPrestigeInfoHandler;
	import com.rpgGame.netData.fate.message.ResFatePanleInfoMessage;
	import com.rpgGame.netData.fate.handler.ResFatePanleInfoHandler;
	import com.rpgGame.netData.fate.message.ResFateInfoMessage;
	import com.rpgGame.netData.fate.handler.ResFateInfoHandler;
	import com.rpgGame.netData.fate.message.ResFateExchangeMessage;
	import com.rpgGame.netData.fate.handler.ResFateExchangeHandler;
	import com.rpgGame.netData.fate.message.ResFateYiDuiHuanMessage;
	import com.rpgGame.netData.fate.handler.ResFateYiDuiHuanHandler;
	import com.rpgGame.netData.rank.message.ResRankExchangeInfoMessage;
	import com.rpgGame.netData.rank.handler.ResRankExchangeInfoHandler;
	import com.rpgGame.netData.destiny.message.ResAcceptDestinyTaskMessage;
	import com.rpgGame.netData.destiny.handler.ResAcceptDestinyTaskHandler;
	import com.rpgGame.netData.destiny.message.ResDestinyInfoMessage;
	import com.rpgGame.netData.destiny.handler.ResDestinyInfoHandler;
	import com.rpgGame.netData.isle.message.ResIslePanlMessage;
	import com.rpgGame.netData.isle.handler.ResIslePanlHandler;
	import com.rpgGame.netData.isle.message.ResIsleTracePanlMessage;
	import com.rpgGame.netData.isle.handler.ResIsleTracePanlHandler;
	import com.rpgGame.netData.moonbox.message.ResMoonBoxItemAddMessageMessage;
	import com.rpgGame.netData.moonbox.handler.ResMoonBoxItemAddMessageHandler;
	import com.rpgGame.netData.moonbox.message.ResMoonBoxItemChangeMessage;
	import com.rpgGame.netData.moonbox.handler.ResMoonBoxItemChangeHandler;
	import com.rpgGame.netData.moonbox.message.ResMoonBoxItemRemoveMessage;
	import com.rpgGame.netData.moonbox.handler.ResMoonBoxItemRemoveHandler;
	import com.rpgGame.netData.moonbox.message.ResSendMoonBoxStoreInfoMessage;
	import com.rpgGame.netData.moonbox.handler.ResSendMoonBoxStoreInfoHandler;
	import com.rpgGame.netData.moonbox.message.ResSendMoonBoxItemInfoMessage;
	import com.rpgGame.netData.moonbox.handler.ResSendMoonBoxItemInfoHandler;
	import com.rpgGame.netData.shiji.message.ResShiJiInfoMessage;
	import com.rpgGame.netData.shiji.handler.ResShiJiInfoHandler;
	import com.rpgGame.netData.taipingcaidian.message.ResTaiPingInfoMessageMessage;
	import com.rpgGame.netData.taipingcaidian.handler.ResTaiPingInfoMessageHandler;
	import com.rpgGame.netData.taipingcaidian.message.ResTaiPingRewardMessage;
	import com.rpgGame.netData.taipingcaidian.handler.ResTaiPingRewardHandler;
	import com.rpgGame.netData.desirepond.message.ResDesirePondPanlMessage;
	import com.rpgGame.netData.desirepond.handler.ResDesirePondPanlHandler;
	import com.rpgGame.netData.desirepond.message.ResDesireSuccessMessage;
	import com.rpgGame.netData.desirepond.handler.ResDesireSuccessHandler;
	import com.rpgGame.netData.qiankundai.message.ResQianKunDaiItemInfosMessage;
	import com.rpgGame.netData.qiankundai.handler.ResQianKunDaiItemInfosHandler;
	import com.rpgGame.netData.qiankundai.message.ResQianKunDaiItemAddMessage;
	import com.rpgGame.netData.qiankundai.handler.ResQianKunDaiItemAddHandler;
	import com.rpgGame.netData.qiankundai.message.ResQianKunDaiItemChangeMessage;
	import com.rpgGame.netData.qiankundai.handler.ResQianKunDaiItemChangeHandler;
	import com.rpgGame.netData.qiankundai.message.ResQianKunDaiItemRemoveMessage;
	import com.rpgGame.netData.qiankundai.handler.ResQianKunDaiItemRemoveHandler;
	import com.rpgGame.netData.royalCity.message.ResCityInfosMessage;
	import com.rpgGame.netData.royalCity.handler.ResCityInfosHandler;
	import com.rpgGame.netData.royalCity.message.ResJingTouZiCaiMessage;
	import com.rpgGame.netData.royalCity.handler.ResJingTouZiCaiHandler;
	import com.rpgGame.netData.royalCity.message.ResShiQiMessage;
	import com.rpgGame.netData.royalCity.handler.ResShiQiHandler;
	import com.rpgGame.netData.royalCity.message.ResThirdCityFightResultMessage;
	import com.rpgGame.netData.royalCity.handler.ResThirdCityFightResultHandler;
	import com.rpgGame.netData.royalCity.message.ResWaitTimeMessage;
	import com.rpgGame.netData.royalCity.handler.ResWaitTimeHandler;
	import com.rpgGame.netData.royalCity.message.ResEnterCityWarMessage;
	import com.rpgGame.netData.royalCity.handler.ResEnterCityWarHandler;
	import com.rpgGame.netData.royalCity.message.ResCityWarStartMessage;
	import com.rpgGame.netData.royalCity.handler.ResCityWarStartHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulExpChangeMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulExpChangeHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulLevelUpMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulLevelUpHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulChangeCountMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulChangeCountHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulDatasMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulDatasHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulChangeModelResultMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulChangeModelResultHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulRewardResultMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulRewardResultHandler;
	import com.rpgGame.netData.fightsoul.message.SCFightSoulChangeModelResultMessage;
	import com.rpgGame.netData.fightsoul.handler.SCFightSoulChangeModelResultHandler;
	import com.rpgGame.netData.lostSkill.message.SCLostSkillInfosMessage;
	import com.rpgGame.netData.lostSkill.handler.SCLostSkillInfosHandler;
	import com.rpgGame.netData.lostSkill.message.SCActvitSkillResultMessage;
	import com.rpgGame.netData.lostSkill.handler.SCActvitSkillResultHandler;
	import com.rpgGame.netData.lostSkill.message.SCChangeSkillResultMessage;
	import com.rpgGame.netData.lostSkill.handler.SCChangeSkillResultHandler;
	import com.rpgGame.netData.lostSkill.message.SCLostSkillLevelUpResultMessage;
	import com.rpgGame.netData.lostSkill.handler.SCLostSkillLevelUpResultHandler;
	import com.rpgGame.netData.meridian.message.SCMeridianListMessage;
	import com.rpgGame.netData.meridian.handler.SCMeridianListHandler;
	import com.rpgGame.netData.meridian.message.SCMeridianInfoMessage;
	import com.rpgGame.netData.meridian.handler.SCMeridianInfoHandler;
	import com.rpgGame.netData.cheats.message.SCCheatsListMessage;
	import com.rpgGame.netData.cheats.handler.SCCheatsListHandler;
	import com.rpgGame.netData.cheats.message.SCCheatsInfoMessage;
	import com.rpgGame.netData.cheats.handler.SCCheatsInfoHandler;
	import com.rpgGame.netData.cheats.message.SCNodeInfoMessage;
	import com.rpgGame.netData.cheats.handler.SCNodeInfoHandler;
	import com.rpgGame.netData.lunjian.message.SCLunJianPanelInfosMessage;
	import com.rpgGame.netData.lunjian.handler.SCLunJianPanelInfosHandler;
	import com.rpgGame.netData.lunjian.message.SCLunJianTimeMessage;
	import com.rpgGame.netData.lunjian.handler.SCLunJianTimeHandler;
	import com.rpgGame.netData.lunjian.message.SCLunJianResultMessage;
	import com.rpgGame.netData.lunjian.handler.SCLunJianResultHandler;
	import com.rpgGame.netData.cooldown.message.ResCooldownInfoListMessage;
	import com.rpgGame.netData.cooldown.handler.ResCooldownInfoListHandler;
	import com.rpgGame.netData.cross.message.ResChangeServerGameToClientMessage;
	import com.rpgGame.netData.cross.handler.ResChangeServerGameToClientHandler;
	import com.rpgGame.netData.client.message.ResClientMessageMessage;
	import com.rpgGame.netData.client.handler.ResClientMessageHandler;
	import com.rpgGame.netData.client.message.ResClientCustomTagMessage;
	import com.rpgGame.netData.client.handler.ResClientCustomTagHandler;
	import com.rpgGame.netData.client.message.TestMessageMessage;
	import com.rpgGame.netData.client.handler.TestMessageHandler;
	import com.rpgGame.netData.dailyzone.message.SCDailyZonePanelInfoMessage;
	import com.rpgGame.netData.dailyzone.handler.SCDailyZonePanelInfoHandler;
	import com.rpgGame.netData.dailyzone.message.SCDailyZoneMonsterCountMessage;
	import com.rpgGame.netData.dailyzone.handler.SCDailyZoneMonsterCountHandler;
	import com.rpgGame.netData.dailyzone.message.SCDailyZoneTimeInfoMessage;
	import com.rpgGame.netData.dailyzone.handler.SCDailyZoneTimeInfoHandler;
	import com.rpgGame.netData.dailyzone.message.SCDailyZoneRewardPanelInfoMessage;
	import com.rpgGame.netData.dailyzone.handler.SCDailyZoneRewardPanelInfoHandler;
	import com.rpgGame.netData.dailyzone.message.SCDailyZoneIdInfoMessage;
	import com.rpgGame.netData.dailyzone.handler.SCDailyZoneIdInfoHandler;
	import flash.utils.Dictionary;
	
	import org.game.netCore.net.Handler;
	import org.game.netCore.net.Message;
	
	/** 
	 * @author Commuication Auto Maker
	 * 
	 * @version 1.0.0
	 * 
	 * 引用类列表
	 */
	public class MessagePool {
		//消息类字典
		private var messages:Dictionary = new Dictionary();
		//处理类字典
		private var handlers:Dictionary = new Dictionary();
		
		public function MessagePool(){
			register(100101, ResCreateCharacterMessage, ResCreateCharacterHandler);
			register(100102, ResLoginSuccessMessage, ResLoginSuccessHandler);
			register(100103, ResSubstituteMessage, ResSubstituteHandler);
			register(100104, ResErrorMessage, ResErrorHandler);
			register(100105, ResQuitMessage, ResQuitHandler);
			register(100106, ResHeartMessage, ResHeartHandler);
			register(101101, ResRoundPlayerMessage, ResRoundPlayerHandler);
			register(101102, ResRoundMonsterMessage, ResRoundMonsterHandler);
			register(101103, ResRoundGoodsMessage, ResRoundGoodsHandler);
			register(101104, ResRoundPetMessage, ResRoundPetHandler);
			register(101105, ResRoundPlayerDisappearMessage, ResRoundPlayerDisappearHandler);
			register(101106, ResRoundMonsterDisappearMessage, ResRoundMonsterDisappearHandler);
			register(101107, ResRoundGoodsDisappearMessage, ResRoundGoodsDisappearHandler);
			register(101108, ResRoundPetDisappearMessage, ResRoundPetDisappearHandler);
			register(101109, ResSetPositionMessage, ResSetPositionHandler);
			register(101110, ResRunPositionsMessage, ResRunPositionsHandler);
			register(101111, ResMonsterRunPositionsMessage, ResMonsterRunPositionsHandler);
			register(101112, ResPlayerJumpPositionsMessage, ResPlayerJumpPositionsHandler);
			register(101113, ResStartBlockMessage, ResStartBlockHandler);
			register(101114, ResStopBlockMessage, ResStopBlockHandler);
			register(101115, ResMonsterStopMessage, ResMonsterStopHandler);
			register(101116, ResPlayerStopMessage, ResPlayerStopHandler);
			register(101117, ResChangeMapMessage, ResChangeMapHandler);
			register(101118, ResWeaponChangeMessage, ResWeaponChangeHandler);
			register(101119, ResArmorChangeMessage, ResArmorChangeHandler);
			register(101120, ResEnterMapMessage, ResEnterMapHandler);
			register(101121, ResPetStopMessage, ResPetStopHandler);
			register(101122, ResPetRunPositionsMessage, ResPetRunPositionsHandler);
			register(101123, ResPlayerRunEndMessage, ResPlayerRunEndHandler);
			register(101124, ResSendLinesMessage, ResSendLinesHandler);
			register(101125, ResRoundObjectsMessage, ResRoundObjectsHandler);
			register(101126, ResChangeMapFailedMessage, ResChangeMapFailedHandler);
			register(101127, ResChangeDirectMessage, ResChangeDirectHandler);
			register(101128, ResChangePositionMessage, ResChangePositionHandler);
			register(101129, ResRoundNpcMessage, ResRoundNpcHandler);
			register(101130, ResRoundNpcDisappearMessage, ResRoundNpcDisappearHandler);
			register(101131, ResRoundEffectMessage, ResRoundEffectHandler);
			register(101132, ResRoundEffectDisappearMessage, ResRoundEffectDisappearHandler);
			register(101133, ResPetJumpPositionsMessage, ResPetJumpPositionsHandler);
			register(101134, ResPetTranMoveMessage, ResPetTranMoveHandler);
			register(101135, ResJumpSetPositionMessage, ResJumpSetPositionHandler);
			register(101136, ResDynamicgridsMessage, ResDynamicgridsHandler);
			register(101137, ResNewRunPositionsMessage, ResNewRunPositionsHandler);
			register(101138, ResChangeSexMessage, ResChangeSexHandler);
			register(101139, ResMoveSpeedCorrectionPercentMessage, ResMoveSpeedCorrectionPercentHandler);
			register(101140, ResShowEffectToClientMessage, ResShowEffectToClientHandler);
			register(101141, ResDoubleRepairInfosToClientMessage, ResDoubleRepairInfosToClientHandler);
			register(101142, ResTaskMoveToClientMessage, ResTaskMoveToClientHandler);
			register(101143, ResPlayerRunFailMessage, ResPlayerRunFailHandler);
			register(101146, ResRoundGoodsExtraMessage, ResRoundGoodsExtraHandler);
			register(101147, ResRoundGoodsMoneyMessage, ResRoundGoodsMoneyHandler);
			register(101148, SCSceneObjMoveMessage, SCSceneObjMoveHandler);
			register(101150, ResHelmChangeMessage, ResHelmChangeHandler);
			register(101151, SCAttachStateChangeMessage, SCAttachStateChangeHandler);
			register(101701, ResSynPlayerPositionMessage, ResSynPlayerPositionHandler);
			register(101702, ResSynMonsterPositionMessage, ResSynMonsterPositionHandler);
			register(101703, ResMapBlocksMessage, ResMapBlocksHandler);
			register(102101, ResFightBroadcastMessage, ResFightBroadcastHandler);
			register(102102, ResAttackResultMessage, ResAttackResultHandler);
			register(102103, ResAttackRangeMessage, ResAttackRangeHandler);
			register(102104, ResEffectBroadcastMessage, ResEffectBroadcastHandler);
			register(102105, ResFightFailedBroadcastMessage, ResFightFailedBroadcastHandler);
			register(102106, ResFightFinishBroadcastMessage, ResFightFinishBroadcastHandler);
			register(102107, ResAttackVentToClientMessage, ResAttackVentToClientHandler);
			register(102108, ResAttackSingingToClientMessage, ResAttackSingingToClientHandler);
			register(102109, ResAttackBreakSingingToClientMessage, ResAttackBreakSingingToClientHandler);
			register(102110, ResAttackBeautyMessage, ResAttackBeautyHandler);
			register(102111, ResSkillClickFlyMessage, ResSkillClickFlyHandler);
			register(102112, ResAttackTargetMessage, ResAttackTargetHandler);
			register(102113, ResVirFightObjectAttackResultMessage, ResVirFightObjectAttackResultHandler);
			register(102114, SCAttackerResultMessage, SCAttackerResultHandler);
			register(102115, SCCancelSkillMessage, SCCancelSkillHandler);
			register(102116, SCBuffSkillMessage, SCBuffSkillHandler);
			register(103101, ResMyPlayerInfoMessage, ResMyPlayerInfoHandler);
			register(103102, ResPlayerAddExpMessage, ResPlayerAddExpHandler);
			register(103103, ResPersonalNoticeMessage, ResPersonalNoticeHandler);
			register(103104, ResPlayerAttributeMessage, ResPlayerAttributeHandler);
			register(103105, BroadcastPlayerAttriChangeMessage, BroadcastPlayerAttriChangeHandler);
			register(103106, ResPlayerAttributesChangeMessage, ResPlayerAttributesChangeHandler);
			register(103107, ResPlayerBriefMessage, ResPlayerBriefHandler);
			register(103108, ResSyncServerTimeMessage, ResSyncServerTimeHandler);
			register(103109, ResPlayerStateChangeMessage, ResPlayerStateChangeHandler);
			register(103110, ResChangePKStateMessage, ResChangePKStateHandler);
			register(103111, ResChangePlayerNameToClientMessage, ResChangePlayerNameToClientHandler);
			register(103112, ResAutoStartStateMessage, ResAutoStartStateHandler);
			register(103113, RespopuGuideMessage, RespopuGuideHandler);
			register(103114, ResPlayerDieMessage, ResPlayerDieHandler);
			register(103115, ResReviveSuccessMessage, ResReviveSuccessHandler);
			register(103116, ResPlayerNonageStateMessage, ResPlayerNonageStateHandler);
			register(103117, NonagePromptMessage, NonagePromptHandler);
			register(103118, ResPlayerNonageTimeMessage, ResPlayerNonageTimeHandler);
			register(103119, ResPlayerNonageRegisterMessage, ResPlayerNonageRegisterHandler);
			register(103120, ResOthersPlayerInfoMessage, ResOthersPlayerInfoHandler);
			register(103121, ResPhoneVerificationStatusMessage, ResPhoneVerificationStatusHandler);
			register(103122, ResCountdownToClientMessage, ResCountdownToClientHandler);
			register(103123, ResRechargeInfoMessage, ResRechargeInfoHandler);
			register(103124, ResTotalOnlineTimeMessage, ResTotalOnlineTimeHandler);
			register(103125, ReskillnumToClientMessage, ReskillnumToClientHandler);
			register(103126, SCPlayerLevelUpMessage, SCPlayerLevelUpHandler);
			register(103127, SCCurrencyChangeMessage, SCCurrencyChangeHandler);
			register(103128, SCMaxValueChangeMessage, SCMaxValueChangeHandler);
			register(103215, SCNoticeMessage, SCNoticeHandler);
			register(103216, SCBroadcastCurrencyChangeMessage, SCBroadcastCurrencyChangeHandler);
			register(104101, ResNpcServicesMessage, ResNpcServicesHandler);
			register(104102, ResStartGatherMessage, ResStartGatherHandler);
			register(104103, ResStopGatherMessage, ResStopGatherHandler);
			register(104104, ResNpcActionMessage, ResNpcActionHandler);
			register(104105, ResTaskNpcGatherFinishMessage, ResTaskNpcGatherFinishHandler);
			register(105100, ResStoreItemInfosMessage, ResStoreItemInfosHandler);
			register(105101, ResStoreItemAddMessage, ResStoreItemAddHandler);
			register(105102, ResStoreItemChangeMessage, ResStoreItemChangeHandler);
			register(105103, ResStoreItemRemoveMessage, ResStoreItemRemoveHandler);
			register(107101, WearEquipItemMessage, WearEquipItemHandler);
			register(107102, UnwearEquipItemMessage, UnwearEquipItemHandler);
			register(107103, ResKindInfosMessage, ResKindInfosHandler);
			register(107104, ResBuTianShenShiKindInfoMessage, ResBuTianShenShiKindInfoHandler);
			register(107105, ResEquipInfoMessage, ResEquipInfoHandler);
			register(107106, ResEquipOperateResultMessage, ResEquipOperateResultHandler);
			register(108101, ResItemInfoMessage, ResItemInfoHandler);
			register(108102, ResItemAddMessage, ResItemAddHandler);
			register(108103, ResItemChangeMessage, ResItemChangeHandler);
			register(108104, ResItemRemoveMessage, ResItemRemoveHandler);
			register(108105, ResUseItemSuccessMessage, ResUseItemSuccessHandler);
			register(108106, ResBackpackFullMessage, ResBackpackFullHandler);
			register(108107, ResTakeUpSuccessMessage, ResTakeUpSuccessHandler);
			register(108108, ResCellTimeMessage, ResCellTimeHandler);
			register(108109, ResOpenCellResultMessage, ResOpenCellResultHandler);
			register(108112, ResPrivateItemInfoMessage, ResPrivateItemInfoHandler);
			register(108113, ResAddPrivateItemMessage, ResAddPrivateItemHandler);
			register(108114, ResRemovePrivateItemMessage, ResRemovePrivateItemHandler);
			register(108115, ResChangeBindItemMessage, ResChangeBindItemHandler);
			register(108116, ResChangeLimitItemMessage, ResChangeLimitItemHandler);
			register(109101, ResTeamInfoMessage, ResTeamInfoHandler);
			register(109102, ResApplyClientMessage, ResApplyClientHandler);
			register(109103, ResLeaveTeamMessage, ResLeaveTeamHandler);
			register(109104, ResInviteTeamMessage, ResInviteTeamHandler);
			register(109105, ResTeamExteriorClientMessage, ResTeamExteriorClientHandler);
			register(109106, ResAppointClientMessage, ResAppointClientHandler);
			register(109111, ResMapSearchTeamInfoClientMessage, ResMapSearchTeamInfoClientHandler);
			register(109112, ResMapSearchPlayerInfoClientMessage, ResMapSearchPlayerInfoClientHandler);
			register(109113, ResTeamSynPosClientMessage, ResTeamSynPosClientHandler);
			register(109114, ResTeamSynMemberinfoClientMessage, ResTeamSynMemberinfoClientHandler);
			register(109115, ResSetTeamOptionsClientMessage, ResSetTeamOptionsClientHandler);
			register(109116, ResGenericSearchToClientMessage, ResGenericSearchToClientHandler);
			register(111101, ResGuildGetGuildListToClientMessage, ResGuildGetGuildListToClientHandler);
			register(111102, ResGuildApplyAddMessage, ResGuildApplyAddHandler);
			register(111103, ResGuildInviteAddMessage, ResGuildInviteAddHandler);
			register(111104, ResGuildGetMemberListMessage, ResGuildGetMemberListHandler);
			register(111105, ResGuildGetEventListMessage, ResGuildGetEventListHandler);
			register(111106, ResGuildGuildInfoMessage, ResGuildGuildInfoHandler);
			register(111108, ResGuildHandleResultMessage, ResGuildHandleResultHandler);
			register(111109, ResNoticeGuildBossApplyMessage, ResNoticeGuildBossApplyHandler);
			register(111110, ResRoundGuildChangeMessage, ResRoundGuildChangeHandler);
			register(111111, ResApplyUnionGuildMessage, ResApplyUnionGuildHandler);
			register(111112, ResGuildDiplomacyInfosMessage, ResGuildDiplomacyInfosHandler);
			register(111113, ResSearchGuildMessage, ResSearchGuildHandler);
			register(111114, ResDevoteGuildMessage, ResDevoteGuildHandler);
			register(111401, ResSendGuildStoreInfoMessage, ResSendGuildStoreInfoHandler);
			register(111402, ResGuildItemAddMessage, ResGuildItemAddHandler);
			register(111403, ResGuildItemChangeMessage, ResGuildItemChangeHandler);
			register(111404, ResGuildItemRemoveMessage, ResGuildItemRemoveHandler);
			register(111405, ResGuildStoreOptAddMessage, ResGuildStoreOptAddHandler);
			register(111406, ResGuildStoreApplylistMessage, ResGuildStoreApplylistHandler);
			register(111501, ResGuildBossListMessage, ResGuildBossListHandler);
			register(111502, ResUpdateGuildBossMessage, ResUpdateGuildBossHandler);
			register(111503, ResGuildZoneResultMessage, ResGuildZoneResultHandler);
			register(112101, ResChatMessage, ResChatHandler);
			register(112102, ResChatRecordMessage, ResChatRecordHandler);
			register(112103, ResOfflineChatCountMessage, ResOfflineChatCountHandler);
			register(114101, ResMonsterHpChangeMessage, ResMonsterHpChangeHandler);
			register(114102, ResMonsterMpChangeMessage, ResMonsterMpChangeHandler);
			register(114103, ResMonsterSpChangeMessage, ResMonsterSpChangeHandler);
			register(114104, ResMonsterMaxHpChangeMessage, ResMonsterMaxHpChangeHandler);
			register(114105, ResMonsterMaxMpChangeMessage, ResMonsterMaxMpChangeHandler);
			register(114106, ResMonsterMaxSpChangeMessage, ResMonsterMaxSpChangeHandler);
			register(114107, ResMonsterSpeedChangeMessage, ResMonsterSpeedChangeHandler);
			register(114108, ResMonsterDieMessage, ResMonsterDieHandler);
			register(114109, ResMonsterReviveMessage, ResMonsterReviveHandler);
			register(114110, ResMonsterSayMessage, ResMonsterSayHandler);
			register(114112, ResMonsterHpRateChangeMessage, ResMonsterHpRateChangeHandler);
			register(114113, ResWGBossListToClientMessage, ResWGBossListToClientHandler);
			register(114114, ResWGBossInfoToClientMessage, ResWGBossInfoToClientHandler);
			register(114115, ResBossDamageInfosToClientMessage, ResBossDamageInfosToClientHandler);
			register(114116, ResMonsterAIStepChangeMessage, ResMonsterAIStepChangeHandler);
			register(114117, ResBossOwerInfoToClientMessage, ResBossOwerInfoToClientHandler);
			register(115201, ResFightPowerToClientMessage, ResFightPowerToClientHandler);
			register(116101, ResFriendListInfoMessage, ResFriendListInfoHandler);
			register(116102, ResOperationFriendResultMessage, ResOperationFriendResultHandler);
			register(116103, ResOperationFriendMsgMessage, ResOperationFriendMsgHandler);
			register(116104, ResPlayerFriendSettingMessage, ResPlayerFriendSettingHandler);
			register(120101, ResAllMailsMessage, ResAllMailsHandler);
			register(120102, ResMailDetailInfoMessage, ResMailDetailInfoHandler);
			register(120103, ResRecevieNewMailMessage, ResRecevieNewMailHandler);
			register(120104, ResGetMailAttachmentSueccessMessage, ResGetMailAttachmentSueccessHandler);
			register(120105, SCDeleteResultMessage, SCDeleteResultHandler);
			register(121101, ResBuffsMessage, ResBuffsHandler);
			register(121102, ResAddBuffMessage, ResAddBuffHandler);
			register(121103, ResRemoveBuffMessage, ResRemoveBuffHandler);
			register(121104, ResBuffInfoMessage, ResBuffInfoHandler);
			register(121105, ResChangeBuffMessage, ResChangeBuffHandler);
			register(121106, ResShowBuffInfoMessage, ResShowBuffInfoHandler);
			register(122101, ResTransactionsLaunchMessage, ResTransactionsLaunchHandler);
			register(122102, ResTransactionsCanceledMessage, ResTransactionsCanceledHandler);
			register(122103, ResTransactionsStartMessage, ResTransactionsStartHandler);
			register(122104, ResTransactionsIntoItemMessage, ResTransactionsIntoItemHandler);
			register(122105, ResTransactionsRemoveItemMessage, ResTransactionsRemoveItemHandler);
			register(122106, ResTransactionsChangeGoldMessage, ResTransactionsChangeGoldHandler);
			register(122107, ResTransactionsChangeYuanbaoMessage, ResTransactionsChangeYuanbaoHandler);
			register(122108, ResTransactionsSetStateMessage, ResTransactionsSetStateHandler);
			register(122109, ResTransactionsSuccessMessage, ResTransactionsSuccessHandler);
			register(122111, ResTransactionsErrorMessage, ResTransactionsErrorHandler);
			register(122112, ResTmpYuanbaoLogMessage, ResTmpYuanbaoLogHandler);
			register(123101, ResSkillInfosMessage, ResSkillInfosHandler);
			register(123102, ResSkillAddMessage, ResSkillAddHandler);
			register(123103, ResSkillStartLevelUpMessage, ResSkillStartLevelUpHandler);
			register(123104, ResSkillRemoveMessage, ResSkillRemoveHandler);
			register(123105, ResSkillResetEffectsidMessage, ResSkillResetEffectsidHandler);
			register(123107, ResSkillChangeMessage, ResSkillChangeHandler);
			register(124101, ResTaskInformationMessage, ResTaskInformationHandler);
			register(124102, ResTaskAcceptedMessage, ResTaskAcceptedHandler);
			register(124103, ResTaskChangeMessage, ResTaskChangeHandler);
			register(124104, ResTaskSubmitedMessage, ResTaskSubmitedHandler);
			register(124105, ResTreasureBoxInfoMessage, ResTreasureBoxInfoHandler);
			register(124106, ResTreasureBoxRewardListMessage, ResTreasureBoxRewardListHandler);
			register(124107, ResGetTreasureBoxRewardMessage, ResGetTreasureBoxRewardHandler);
			register(125101, SCMeritoriousInfoListMessage, SCMeritoriousInfoListHandler);
			register(125103, SCMeritoriousUpgradeResultMessage, SCMeritoriousUpgradeResultHandler);
			register(126101, SCJunJieInfoListMessage, SCJunJieInfoListHandler);
			register(126103, SCJunJieActivateResultMessage, SCJunJieActivateResultHandler);
			register(126104, SCJunJieInfoUpdateListMessage, SCJunJieInfoUpdateListHandler);
			register(126105, SCUpdateRoundMessage, SCUpdateRoundHandler);
			register(137201, ResCardToClientMessage, ResCardToClientHandler);
			register(141101, ResToplistToClientMessage, ResToplistToClientHandler);
			register(141102, ResListLeaderToClientMessage, ResListLeaderToClientHandler);
			register(141103, ResWorshipValueMessage, ResWorshipValueHandler);
			register(141104, ResRankRewardMessage, ResRankRewardHandler);
			register(141105, ResWorshipCountMessage, ResWorshipCountHandler);
			register(142101, ResStallGoodsMessage, ResStallGoodsHandler);
			register(142102, ResStallInfoMessage, ResStallInfoHandler);
			register(142103, ResChangeStallNameMessage, ResChangeStallNameHandler);
			register(142104, ResStallGoodsSearchMessage, ResStallGoodsSearchHandler);
			register(142105, ResLookStallLogMessage, ResLookStallLogHandler);
			register(144101, SCHorseAllInfoToClientMessage, SCHorseAllInfoToClientHandler);
			register(144103, SCHorseIllusionToClientMessage, SCHorseIllusionToClientHandler);
			register(144105, SCHorseUpResultToClientMessage, SCHorseUpResultToClientHandler);
			register(144106, SCExtraItemNumMessage, SCExtraItemNumHandler);
			register(148101, ResPetDieBroadcastMessage, ResPetDieBroadcastHandler);
			register(148102, ResPetTargetMessage, ResPetTargetHandler);
			register(148103, ResPetHpChangeMessage, ResPetHpChangeHandler);
			register(148104, ResPetDebutMessage, ResPetDebutHandler);
			register(148105, ResPetListMessage, ResPetListHandler);
			register(148106, ResPetAttributeMessage, ResPetAttributeHandler);
			register(148107, ResPetRankChangeMessage, ResPetRankChangeHandler);
			register(148108, ResPetReliefTimeMessage, ResPetReliefTimeHandler);
			register(149101, SCSaleSuccessMessage, SCSaleSuccessHandler);
			register(149102, SCRebuySuccessMessage, SCRebuySuccessHandler);
			register(149103, SCRebuyItemInfosMessage, SCRebuyItemInfosHandler);
			register(149105, SCBuyItemResultMessage, SCBuyItemResultHandler);
			register(149106, SCSendShopListMessage, SCSendShopListHandler);
			register(149107, SCSendShopItemChangeMessage, SCSendShopItemChangeHandler);
			register(153101, ResSendAchievementDataInfoMessage, ResSendAchievementDataInfoHandler);
			register(153102, ResSendFinishAchievementMessage, ResSendFinishAchievementHandler);
			register(153103, ResSendGetAchievementAwardMessage, ResSendGetAchievementAwardHandler);
			register(154101, ResSendSignInfoToClientMessage, ResSendSignInfoToClientHandler);
			register(154102, ResSendSignResultToClientMessage, ResSendSignResultToClientHandler);
			register(154103, ResSignSumAwardResultToClientMessage, ResSignSumAwardResultToClientHandler);
			register(155104, ResZoneFailureToClientMessage, ResZoneFailureToClientHandler);
			register(155105, ResZoneCommonPanelInfoMessage, ResZoneCommonPanelInfoHandler);
			register(155106, ResZoneCommonTrackInfoMessage, ResZoneCommonTrackInfoHandler);
			register(155107, ResZoneCommonTrackCompactInfoMessage, ResZoneCommonTrackCompactInfoHandler);
			register(155108, ResZoneCommonResultInfoMessage, ResZoneCommonResultInfoHandler);
			register(155109, ResJuegMingTaInfoMessage, ResJuegMingTaInfoHandler);
			register(155110, ResJueMingTaSweepInfoMessage, ResJueMingTaSweepInfoHandler);
			register(155111, ResJiaoChangInfoMessage, ResJiaoChangInfoHandler);
			register(155112, ResJiaoChangResultInfoMessage, ResJiaoChangResultInfoHandler);
			register(155113, ResTreeAndMonsterRewardInfoMessage, ResTreeAndMonsterRewardInfoHandler);
			register(155130, ResSuMingDuiJueInfoMessage, ResSuMingDuiJueInfoHandler);
			register(155131, ResLeaderBossPanelInfoMessage, ResLeaderBossPanelInfoHandler);
			register(155132, ResWuShenDianFightInfoMessage, ResWuShenDianFightInfoHandler);
			register(155133, ResWuShenDianRewardInfoMessage, ResWuShenDianRewardInfoHandler);
			register(155134, ResBossGuideInfoMessage, ResBossGuideInfoHandler);
			register(155135, ResWuShenDianAnimationMessage, ResWuShenDianAnimationHandler);
			register(155136, SCClientTriggerValiedMessage, SCClientTriggerValiedHandler);
			register(155137, SCEnterZoneMessage, SCEnterZoneHandler);
			register(155138, SCOutZoneMessage, SCOutZoneHandler);
			register(155139, SCZoneStageChangeMessage, SCZoneStageChangeHandler);
			register(155140, SCRemainTimeMessage, SCRemainTimeHandler);
			register(155141, SCKillInfosMessage, SCKillInfosHandler);
			register(155142, SCKillInfoMessage, SCKillInfoHandler);
			register(155143, SCCurTriggerMessage, SCCurTriggerHandler);
			register(155144, SCMultiZoneResultMessage, SCMultiZoneResultHandler);
			register(155145, SCMultiZoneRewardMessage, SCMultiZoneRewardHandler);
			register(155146, SCMultiZonePanelInfosMessage, SCMultiZonePanelInfosHandler);
			register(155147, SCMultiZonePanelSingleInfoMessage, SCMultiZonePanelSingleInfoHandler);
			register(160101, ResHuntItemAddMessageMessage, ResHuntItemAddMessageHandler);
			register(160102, ResHuntItemChangeMessage, ResHuntItemChangeHandler);
			register(160103, ResHuntItemRemoveMessage, ResHuntItemRemoveHandler);
			register(160104, ResSendHuntStoreInfoMessage, ResSendHuntStoreInfoHandler);
			register(160105, ResSendHuntHistoryInfoMessage, ResSendHuntHistoryInfoHandler);
			register(160106, ResHuntPanlInfoMessage, ResHuntPanlInfoHandler);
			register(160107, ResHuntRewardInfosMessage, ResHuntRewardInfosHandler);
			register(181101, ResActivitiesInfoMessage, ResActivitiesInfoHandler);
			register(181102, ResActivitiesGetRewardInfoMessage, ResActivitiesGetRewardInfoHandler);
			register(181103, ResActivitiesRefreshMessage, ResActivitiesRefreshHandler);
			register(182101, ResNewActivitiesInfoMessage, ResNewActivitiesInfoHandler);
			register(182103, ResNewGetRewardMessage, ResNewGetRewardHandler);
			register(191101, ResVipPanelMessage, ResVipPanelHandler);
			register(192101, ResGrownInfoMessage, ResGrownInfoHandler);
			register(192102, ResGotSuccessMessage, ResGotSuccessHandler);
			register(193101, ResWarMarkListMessage, ResWarMarkListHandler);
			register(193102, ResUpdateWarmarkMessage, ResUpdateWarmarkHandler);
			register(200101, ResGmLevelMessage, ResGmLevelHandler);
			register(201101, ResDropRollItemInfoMessage, ResDropRollItemInfoHandler);
			register(201102, ResDropRollResultInfoMessage, ResDropRollResultInfoHandler);
			register(201103, ResGetRollItemMessage, ResGetRollItemHandler);
			register(204101, ResRefiningInfoMessage, ResRefiningInfoHandler);
			register(204102, ResStrengthenResultMessage, ResStrengthenResultHandler);
			register(204103, ResRefiningItemInfosMessage, ResRefiningItemInfosHandler);
			register(204104, ResExchangeResultMessage, ResExchangeResultHandler);
			register(205101, ResSendVitalityInfoMessage, ResSendVitalityInfoHandler);
			register(209101, ResOfflineAwardPanelMessage, ResOfflineAwardPanelHandler);
			register(209102, ResOfflineResPanelMessage, ResOfflineResPanelHandler);
			register(209103, ResGetOfflineSucMessage, ResGetOfflineSucHandler);
			register(209104, ResGetResSuccessMessage, ResGetResSuccessHandler);
			register(210101, ResDropRollItemInfoMessage, ResDropRollItemInfoHandler);
			register(210102, ResDropRollResultInfoMessage, ResDropRollResultInfoHandler);
			register(210103, ResGetRollItemMessage, ResGetRollItemHandler);
			register(212101, ResPrestigeInfoMessage, ResPrestigeInfoHandler);
			register(213101, ResFatePanleInfoMessage, ResFatePanleInfoHandler);
			register(213102, ResFateInfoMessage, ResFateInfoHandler);
			register(213103, ResFateExchangeMessage, ResFateExchangeHandler);
			register(213104, ResFateYiDuiHuanMessage, ResFateYiDuiHuanHandler);
			register(214101, ResRankExchangeInfoMessage, ResRankExchangeInfoHandler);
			register(215101, ResAcceptDestinyTaskMessage, ResAcceptDestinyTaskHandler);
			register(215102, ResDestinyInfoMessage, ResDestinyInfoHandler);
			register(216101, ResIslePanlMessage, ResIslePanlHandler);
			register(216102, ResIsleTracePanlMessage, ResIsleTracePanlHandler);
			register(217101, ResMoonBoxItemAddMessageMessage, ResMoonBoxItemAddMessageHandler);
			register(217102, ResMoonBoxItemChangeMessage, ResMoonBoxItemChangeHandler);
			register(217103, ResMoonBoxItemRemoveMessage, ResMoonBoxItemRemoveHandler);
			register(217104, ResSendMoonBoxStoreInfoMessage, ResSendMoonBoxStoreInfoHandler);
			register(217105, ResSendMoonBoxItemInfoMessage, ResSendMoonBoxItemInfoHandler);
			register(218101, ResShiJiInfoMessage, ResShiJiInfoHandler);
			register(219101, ResTaiPingInfoMessageMessage, ResTaiPingInfoMessageHandler);
			register(219102, ResTaiPingRewardMessage, ResTaiPingRewardHandler);
			register(220101, ResDesirePondPanlMessage, ResDesirePondPanlHandler);
			register(220102, ResDesireSuccessMessage, ResDesireSuccessHandler);
			register(221100, ResQianKunDaiItemInfosMessage, ResQianKunDaiItemInfosHandler);
			register(221101, ResQianKunDaiItemAddMessage, ResQianKunDaiItemAddHandler);
			register(221102, ResQianKunDaiItemChangeMessage, ResQianKunDaiItemChangeHandler);
			register(221103, ResQianKunDaiItemRemoveMessage, ResQianKunDaiItemRemoveHandler);
			register(222501, ResCityInfosMessage, ResCityInfosHandler);
			register(222502, ResJingTouZiCaiMessage, ResJingTouZiCaiHandler);
			register(222503, ResShiQiMessage, ResShiQiHandler);
			register(222504, ResThirdCityFightResultMessage, ResThirdCityFightResultHandler);
			register(222505, ResWaitTimeMessage, ResWaitTimeHandler);
			register(222506, ResEnterCityWarMessage, ResEnterCityWarHandler);
			register(222507, ResCityWarStartMessage, ResCityWarStartHandler);
			register(223001, SCFightSoulExpChangeMessage, SCFightSoulExpChangeHandler);
			register(223002, SCFightSoulLevelUpMessage, SCFightSoulLevelUpHandler);
			register(223003, SCFightSoulChangeCountMessage, SCFightSoulChangeCountHandler);
			register(223004, SCFightSoulDatasMessage, SCFightSoulDatasHandler);
			register(223005, SCFightSoulChangeModelResultMessage, SCFightSoulChangeModelResultHandler);
			register(223006, SCFightSoulRewardResultMessage, SCFightSoulRewardResultHandler);
			register(223505, SCFightSoulChangeModelResultMessage, SCFightSoulChangeModelResultHandler);
			register(224501, SCLostSkillInfosMessage, SCLostSkillInfosHandler);
			register(224502, SCActvitSkillResultMessage, SCActvitSkillResultHandler);
			register(224503, SCChangeSkillResultMessage, SCChangeSkillResultHandler);
			register(224504, SCLostSkillLevelUpResultMessage, SCLostSkillLevelUpResultHandler);
			register(225101, SCMeridianListMessage, SCMeridianListHandler);
			register(225102, SCMeridianInfoMessage, SCMeridianInfoHandler);
			register(226101, SCCheatsListMessage, SCCheatsListHandler);
			register(226102, SCCheatsInfoMessage, SCCheatsInfoHandler);
			register(226103, SCNodeInfoMessage, SCNodeInfoHandler);
			register(227501, SCLunJianPanelInfosMessage, SCLunJianPanelInfosHandler);
			register(227502, SCLunJianTimeMessage, SCLunJianTimeHandler);
			register(227503, SCLunJianResultMessage, SCLunJianResultHandler);
			register(228100, ResCooldownInfoListMessage, ResCooldownInfoListHandler);
			register(250101, ResChangeServerGameToClientMessage, ResChangeServerGameToClientHandler);
			register(301101, ResClientMessageMessage, ResClientMessageHandler);
			register(301102, ResClientCustomTagMessage, ResClientCustomTagHandler);
			register(301133, TestMessageMessage, TestMessageHandler);
			register(400101, SCDailyZonePanelInfoMessage, SCDailyZonePanelInfoHandler);
			register(400102, SCDailyZoneMonsterCountMessage, SCDailyZoneMonsterCountHandler);
			register(400103, SCDailyZoneTimeInfoMessage, SCDailyZoneTimeInfoHandler);
			register(400104, SCDailyZoneRewardPanelInfoMessage, SCDailyZoneRewardPanelInfoHandler);
			register(400105, SCDailyZoneIdInfoMessage, SCDailyZoneIdInfoHandler);
		}
		
		private function register(id: int, messageClass: Class, handlerClass: Class): void{
			messages[id] = messageClass;
			handlers[id] = handlerClass;
		}
		
		public function getMessage(id: int) : Message{
			if(messages[id] == null) return null;
			else return new messages[id] as Message;
		}
		
		public function getHandler(id: int) : Handler{
			if(handlers[id] == null) return null;
			else return new handlers[id] as Handler;
		}
	}
}